[package]
name = "ddm"
version = "0.1.0"
edition = "2021"

[dependencies]
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
socket2 = { version = "0.4.7", features = ["all"] }
ispf = { git = "https://github.com/oxidecomputer/ispf" }
serde = { version = "1.0.150", features = ["derive"] }
hostname = "0.3.1"
thiserror = "1.0.37"
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
schemars = { version = "0.8.0", features = [ "uuid" ] }
tokio = { version = "1.21", features = ["full"] }
serde_repr = "0.1.9"
anyhow = "1.0.66"
hyper = "0.14.23"
serde_json = "1.0.89"
libnet = { git = "https://github.com/oxidecomputer/netadm-sys", branch = "ddm" }

[dependencies.dpd-client]
git = "https://github.com/oxidecomputer/dendrite"
rev = "854890b7db8347d3ab4c7546b18dc51e5995894c"
package = "dpd-client"

[dependencies.dendrite-common]
git = "https://github.com/oxidecomputer/dendrite"
rev = "854890b7db8347d3ab4c7546b18dc51e5995894c"
package = "common"
