[package]
name = "ddm"
version = "0.1.0"
edition = "2021"

[dependencies]
icmpv6 = { path = "../icmpv6" }
tokio = { version = "1.15", features = ["full"] }
libnet = { git = "https://github.com/oxidecomputer/netadm-sys", branch = "siocgnds" }
socket2 = { version = "0.4", features = ["all"] }
anyhow = "1"
thiserror = "1"
util = { path = "../util" }
slog = "2.7"
slog-term = "2.7"
slog-async = "2.7"
slog-envlogger = "2.2"
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
schemars = { version = "0.8.0", features = [ "uuid" ] }
serde = "1.0"
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }

[dependencies.dpd-api]
git = "https://github.com/oxidecomputer/dendrite"
package = "dpd-api"
branch = "softnpu"

[dependencies.dendrite-common]
git = "https://github.com/oxidecomputer/dendrite"
package = "common"
branch = "softnpu"
